[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.gunicorn",
  "python312Packages.flask",
  "python312Packages.mysql-connector",
  "python312Packages.python-dotenv",
  "python312Packages.pdfkit",
  "wkhtmltopdf" # for PDF generation
]

[phases.install]
cmds = ["echo 'Using Nix to install dependencies, skipping pip.'"]

[start]
cmd = "gunicorn app:app"
